#!/bin/sh
#
# Download and install node, snowfish version
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e
git pull origin mynode
./configure
make -j8
sudo make install
