#!/bin/sh
#
# Download and install node, snowfish version
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

git pull origin mynode
git pull upstream v0.6
mkdir -p ~/.node
./configure --prefix=~/.node
make -j8
make install
git push origin mynode
